
server:
  port: 8080

spring:
  datasource:
    username: root
    password: 145818197cat9
    url: jdbc:mysql://localhost:3306/xiaotao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
